### ISSUE TITLE
Question about state mutation in a "get" method

### ISSUE THREAD

**Issue by tszumowski** [Bumper-Fi/1a-bootstrap-contracts#1]
@industrialist I was looking through the code and had a question (minor, low urgency). Specifically, I was looking through the private method `getBumpAllocation`. 
https://github.com/Bumper-Fi/1a-bootstrap-contracts/blob/6756c093813b6db826d25ae821f61e355c6a1305/BumpMarket.sol#L460-L463

Inside that method, even though it's marked `get`, I believe it may be mutating global state, specifically `bumpRewardAllocation` in 
https://github.com/Bumper-Fi/1a-bootstrap-contracts/blob/6756c093813b6db826d25ae821f61e355c6a1305/BumpMarket.sol#L473
and
`bumpPurchaseAllocation` in 
https://github.com/Bumper-Fi/1a-bootstrap-contracts/blob/6756c093813b6db826d25ae821f61e355c6a1305/BumpMarket.sol#L479

While this is a private method, it didn't seem any of the other `get` methods were mutating inside them. Is that expected behavior?

**Comment by industrialist** [comment]
Hey @tszumowski . Apologies, only just saw this one. All of our dev activity is in elsewhere!

Good point on this. Yes, it is expected behaviour - it probably not be prefixed with a 'get'. I've had a quick chat with the team about it. :+1:
